FROM python:3.12
WORKDIR /app

RUN pip install --upgrade pip

COPY --chown=1001 backend/requirements.txt .

RUN pip install -r requirements.txt

COPY --chown=1001 . .

CMD ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
