services:
  backend:
    build:
      context: ..
      dockerfile: docker_local/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - static:/static
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ..
      dockerfile: docker_local/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app/build

volumes:
  static:
  frontend: